# Autostart
exec-once = waybar #system bar
exec-once = awww-daemon # wallpaper manager
exec-once = awww img ~/Pictures/wallpapers/lofi-cozy-house-rainy-day.jpg
exec-once = mako

exec-once = Telegram -startintray
#exec-once = mcontrolcenter -startintray #not working by msi-ec driver

exec-once = wl-clipboard-history-t # clipboard
exec-once = wl-paste --watch cliphist store
exec-once = systemctl --user restart pipewire #to avoid bugs

exec-once = hypridle
