#for room
$color0 = rgba(d3bda6ee) #active_border_gradient1
$color1 = rgba(847668ee) #active_border_gradient2
$color2 = rgba(6a5f53aa) #inactive_border

#for rainy
#$color0 = rgba(156e3dee)
#$color1 = rgba(1a4f13ee)
#$color2 = rgba(307070aa)
