source = ~/.config/hypr/config/colors.conf

# Window decoration
general {
  gaps_in  = 3
  gaps_out = 5

  border_size = 2

  col.active_border = $color0 $color1 45deg
  col.inactive_border = $color2

  resize_on_border = true
}


decoration {
  rounding = 16

  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
    enabled = true
    size = 5
    passes = 2
  }
}

animations {
  enabled = true

  bezier = myBezier, 0.05, 0.9, 0.1, 1.1

  animation = windows, 1, 7, myBezier
  animation = windowsOut, 1, 7, default, popin 80%
  animation = border, 1, 10, default
  animation = borderangle, 1, 8, default
  animation = fade, 1, 7, default
  animation = workspaces, 1, 6, default
}

master {
  new_status = master
}

# Window rules
# hyprctl clients - show active apps on windows and workspaces

#windowrule = size 1920 1026,^($browser)$
#windowrule = float,^($browser)$
#windowrule = center,^($browser)$
#windowrule = workspace 3, title:^($browser)$

#windowrule = size 940 1026, title:^(org.telegram.desktop)$
#windowrule = move 967 42, title:^(org.telegram.desktop)$
#windowrule = float, title:^(org.telegram.desktop)$
#windowrule = workspace 4, title:^(org.telegram.desktop)$

#windowrule = size 940 1026, title:^($fileManager)$
#windowrule = move 12 42, title:^($fileManager)$
#windowrule = float, title:^($fileManager)$

#windowrule = size 900 600,^(lutris)$
#windowrule = float,^(lutris)$
#windowrule = center,^(lutris)$


windowrule = opacity 0.8 override 0.7 override, match:class kitty
windowrule = opacity 0.8 override, match:class waybar
windowrule = no_initial_focus on, match:title ^win[0-9]+
