# Monitor config
source = ~/.config/hypr/config/output.conf

# Input config
source = ~/.config/hypr/config/input.conf

# Environment config
source = ~/.config/hypr/config/env.conf

# Windows design config
source = ~/.config/hypr/config/windows.conf

# Autostart
source = ~/.config/hypr/config/autostart.conf

# Keybindings
source = ~/.config/hypr/config/keys.conf

# Ecosystem config
source = ~/.config/hypr/config/ecosystem.conf
